title: Osman Ulger
logo: /img/Ozzy.jpg
description: Machine Learning/Computer Vision Engineer | PhD Graduate in Computer Vision at University of Amsterdam
show_downloads: true
google_analytics: 
theme: jekyll-theme-minimal